name: nuxify_widgetbook
description: "A new Flutter project."
publish_to: "none"
version: 1.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^5.1.0
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
