name: nuxify_widgetbook_core
description: "A new Flutter project."
publish_to: "none"
version: 1.7.3

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
